# Site settings
title: Eternity Wall Blog
header-img: img/the-great-wall-of-china-291.jpg
email: feedback@eternitywall.it
description: "Eternity Wall, messages lasting forever. Posts a little less..."
baseurl: ""
url: "http://blog.eternitywall.it"
twitter_username: eternitywall
github_username:  RCasatta

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
